name: .NET 7 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.401' # Use the specific version of .NET 7 you are using

    - name: Restore dependencies
      run: dotnet restore initiate-rest-api/Initiate/Initiate.sln

    - name: Build
      run: dotnet build initiate-rest-api/Initiate/Initiate.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test initiate-rest-api/Initiate/Initiate.sln --no-build --verbosity normal

    - name: Publish
      run: dotnet publish initiate-rest-api/Initiate/Initiate.WebAPI/Initiate.WebAPI.csproj --no-build --configuration Release --output publish
