name: .NET 7 Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.401'  # Specify the .NET 7 version to match your project requirements

    - name: Restore dependencies
      run: dotnet restore ./Initiate/Initiate.sln

    - name: Build solution
      run: dotnet build ./Initiate/Initiate.sln --no-restore --configuration Release

    - name: Publish project
      run: dotnet publish ./Initiate/Initiate.WebAPI/Initiate.WebAPI.csproj --no-build --configuration Release --output publish
